stages:
 - build

Ubuntu:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - module load webstreamer poco-1.8.1 webstreamer
  - export BUILD_GENERATOR="Ninja"
  - export CMAKE_EXTRA_ARGS="-DREMO_WITH_EXAMPLES=ON -DCMAKE_PREFIX_PATH=\"$WEBSTREAMER_DIR;$POCO_DIR\""
  - bash .gitlab-ci.sh
 tags:
  - ubuntu
